import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="facebook-domain-verification" content="6k4rvkgksvwv05x05bwu68ke0fc7db" />
      </Head>

      <main className={styles.main}>
        Site da Lari
      </main>
    </div>
  )
}
