import Head from 'next/head'
import Image from 'next/image'
import { PixelInitial } from '../facebook/PixelInitial'
import styles from '../styles/Home.module.css'

export default function Obrigado() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Obrigado | Larissa Silberman</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="facebook-domain-verification" content="6k4rvkgksvwv05x05bwu68ke0fc7db" />
        <PixelInitial />
      </Head>

      <main className={styles.main}>
        Obrigado pela compra!
      </main>
    </div>
  )
}
