import Head from 'next/head'
import { PixelObrigado } from '../facebook/PixelObrigado'

export default function Obrigado() {
  return (
    <div>
      <Head>
        <title>Obrigado | Larissa Silberman</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="facebook-domain-verification" content="6k4rvkgksvwv05x05bwu68ke0fc7db" />
        <PixelObrigado />
      </Head>

      <main>
        Obrigado pela compra!
      </main>
    </div>
  )
}
